server:
  port: 8080
logging:
  file:
    path: /var/log
  level:
    org:
      springframework:
        security: debug
      flywaydb: debug
cors:
  allowedOrigins: http://localhost,https://localhost
  allowedMethods: "*"
  allowedHeaders: "*"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wuan?allowMultiQueries=true
    username: wuan
    password: wuan
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: wuan
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
  rabbitmq:
    host: localhost
    username: wuan
    password: wuan
    port: 5672
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: ${JWT_SECRET:secret}
  expiration-min: ${JWT_EXPIRATION_MIN:100}
  cookie-name: ${JWT_COOKIE_NAME:jwt}
static-resource:
  handler: classpath:public/
  locations: classpath:public/
